---
- name: (Windows) Create a Temporary Download Location
  win_file:
    path: C:\Temp
    state: directory

- name: (Windows) Download the Rubrik Connector
  win_get_url:
    url: "https://{{ rubrik_cluster_ip }}/connector/RubrikBackupService.zip"
    dest: C:\Temp\RubrikBackupService.zip
    validate_certs: no
    force: no

- name: (Windows) Unzip the Connector Archive
  win_unzip:
    src: C:\Temp\RubrikBackupService.zip
    dest: C:\Temp\

- name: (Windows) Install the Rubrik Connector
  win_package:
    path: C:\Temp\RubrikBackupService.msi
    state: present
    creates_service: 'Rubrik Backup Service'
    wait: yes

- name: (Windows) Set Logon for the Rubrik Connector Service
  win_service:
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    name: 'Rubrik Backup Service'


    