---
- name: (Red Hat) Download the Rubrik Connector
  get_url:
    url: "https://{{ rubrik_cluster_ip }}/connector/rubrik-agent.x86_64.rpm"
    dest: /tmp/rubrik-agent.x86_64.rpm
    validate_certs: no
    force: no
  
- name: (Red Hat) Install the Connector 
  yum:
    name: /tmp/rubrik-agent.x86_64.rpm
    state: present

- name: (Red Hat) Start and Enable the Rubrik Services (RHEL 6)
  service:
    name: rubrikagents
    state: started
    enabled: yes
  when: ansible_distribution_major_version == "6"

- name: (Red Hat) Start and Enable the Rubrik Services (RHEL 7+)
  systemd:
    name: rubrikagents
    state: started
    enabled: yes
  when: ansible_distribution_major_version|int > 6

- name: (Red Hat) Configure iptables (RHEL 6)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: {{ item }}
    source: {{ rubrik_cluster_ip }}
    jump: ACCEPT
    comment: "Opens port to allow a Rubrik cluster to contact the Rubrik Backup Agents on this machine in order to perform backup-related operations."
  with_items:
     - 12800
     - 12801
  when: configure_rhel_firewalld and ansible_distribution_major_version == "6"



- name: Define the Rubrik Service for FirewallD (RHEL 7+)
  template:
    src: rubrikagents.xml
    dest: /etc/firewalld/services/
  when: configure_rhel_firewalld and ansible_distribution_major_version|int > 6

- name: Restart FirewallD (RHEL 7+)
  service:
    name: firewalld
    state: restarted
  when: configure_rhel_firewalld and ansible_distribution_major_version|int > 6

- name: Add the Rubrik Service to FirewallD (RHEL 7+)
  firewalld:
    zone: public
    service: rubrikagents
    permanent: yes
    state: enabled
  when: configure_rhel_firewalld and ansible_distribution_major_version|int > 6

- name: Restart FirewallD (RHEL 7+)
  service:
    name: firewalld
    state: restarted
  when: configure_rhel_firewalld and ansible_distribution_major_version|int > 6